apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: engineering-platform

resources:
  - operator-deployment.yaml
  - operator-api-ingress.yaml

images:
  - name: olivercodes01/teams-operator
    newName: teams-operator
    newTag: local

patches:
  - target:
      kind: Deployment
      name: teams-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: "INFO"
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://teams-api-service.teams-api.svc.cluster.local:4200"



    