apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: engineering-platform

resources:
- ingress.yaml
- namespace.yaml
- teams-api-deployment.yaml
- teams-api-service.yaml
- teams-ui-deployment.yaml
- teams-ui-service.yaml

configMapGenerator:
- name: teams-ui-nginx-conf
  files:
  - default.conf=nginx.conf
  options:
    disableNameSuffixHash: true

images:
- name: teams-ui
  newtag: local-v1
